sudo: required

services:
    - docker

env:
    global:
        # DOCKER_USERNAME
        - secure: OAIF/2Lh/Lq29D8FyAdZQLmIQBGoIVU7Py90EMw3BD5AuSeOkZ0/LblRqDOVQN5AxVXNEqOBsrgtXQobVrWQ+3hOgQKlPS0xNxBss6o//JeWmLbMyhWiLnvM0mNm1963bKxVqrWHXnye+j3CEGPLN+asukIuV2z/12hLKOc0sn5NrlsZENSVRGclvZy1ZUUEfGktm8K3N/6uiWHCMVDpJuiiKajcnTuJ8xmjKKbtZqa8O0J9oYBJ7aTeU0eAe5RvBDd7z0crrv0w4Ul0aoI97220l1Ng8Hlsaf3AHITAfh6uYDBdyybltBx0BjvaI2RIFcV2sSgo6tVQqQSZ1M1eTci0wXW1UJRKAjjVrwlhoaXDE5CcwMEhJuZ93cSa0glcsI6ZbvvZudJxqLYnixGxq/6/PSY8lW5wGyu+5NPZFiYoEPm1pPeroWdkLj+fIAMN4qs6UDvfXPp5qtDSKZmskw/myYGUK+a4ih8j4z4287jvGlmqarC7zvOXgualwurKSjrzz1j/E6S6xNrOAD5JF/kBgc1QIkViYuxK3AXFboNeLoZJDfekiDndjrb/JEP5AFeRbKiZq1s0J9tSVpCX31mh2lDBOsCr4FxAMnVBKMnUFQp+1UYmuuCXI1PamZhSlS9ujRR0yNZUQgl7gmDEjikkTJN+ecf5pwxwkp1Yvis=
        # DOCKER_PASSWORD
        - secure: yRbmPQJwELisqx6VsC7W6AkjD82arre552XwPAv9MPsxo5lWhvjCUpf7bHlARaTyKZkd39HUWFhKSJZySmhh+uUiLlBrXsZEPD0N5MAjEJDCo0zNdiUkswJjvw8/RabfsMM31hiSn3BcS9mF85vZYmnDwhp5I5xseKWfrTyCrCc5Yz0UT4rC4LbugNKBgt442VJIOm06CGVfaDcJrUXf7V6prKa1Nh8XUJQ9IIZg1PKxiW0TeZHbBvkLJhba1XZ+hvUHF4Su3PvMT9xPNqj8i4kKaBJndMQ2JzP+af/b24kf3Mje9RVD+UpyCMbltsdL1zHzql94jpJhdZ4XNCzScqPkR6hgjMcR/UzVT0R852zETbNJb/UXnJknj6NIzxEMhZG0cWq/uLA1ml80PpjhPA8Li0DbGHWrv/2dQ+blvmGTIsFRARiig5bXA677F/FCUi1KcIrdxZQAxWD+v5x8h434x6S+9Ry05yAVUOioYnmWtlc0Fik/5Q9pSpUA8XiHeBaAl5giouvyQXj6YCmrD3/wGbODUEEeQvrbEl3acUbdpA/ffUSb328BCjHs/Ugh5cdMW3WUGeXKlIXWE36cOydw3AOGo/sd+H56FGN9fBXqJ/LAh64nogT9WJZ8Hi5Nb6ncK6rvKwq0800NQCjbP0mpsrHky9f2M0uoUzMaQIY=

install:
    - bash project buildProductionImages

script:
    - docker-compose -f docker-compose.ci.yml up -d
    - docker-compose -f docker-compose.ci.yml run node bin/waitForIt application:80 --timeout=120 -- bin/waitForIt selenium:4444 --timeout=120 -- node_modules/codeceptjs/bin/codecept.js run --steps
    - docker-compose -f docker-compose.ci.yml down -v

deploy:
    provider: script
    script: bash project pushProductionImages
    on:
       branch: master
